# Autogenerated by Migen
set -e

xst -ifn urukul.xst

ngdbuild  -uc urukul.ucf urukul.ngc urukul.ngd

cpldfit -ofmt verilog -optimize speed -unused pullup -iostd LVCMOS33 -p xc2c256-6-ft256 urukul.ngd
taengine -f urukul.vm6 -detail -iopath -l urukul.tim
hprep6 -s IEEE1532 -i urukul.vm6
